<?php
	/* $Id$ */

	if (!extension_loaded('onphp')) {
		echo 'Trying to load onPHP extension.. ';
		
		if (!@dl('onphp.so')) {
			echo "failed.\n";
		} else {
			echo "done.\n";
		}
	}
	
	$config = dirname(__FILE__).'/config.inc.php';
	
	require is_readable($config) ? $config : $config.'.tpl';
	
	$reporter = php_sapi_name() == 'cli' ? new TextReporter() : new HtmlReporter();
	
	$test = new GroupTest('onPHP-'.ONPHP_VERSION);
	
	foreach (glob(ONPHP_TEST_PATH.'{core,main}/*.class.php', GLOB_BRACE) as $file)
		$test->addTestFile($file);
	
	// meta, DB and DAOs ordered tests portion
	if (isset($dbs) && $dbs) {
		Singleton::getInstance('DBTestPool', $dbs)->connect();
		
		// build stuff from meta
		
		$metaDir = ONPHP_TEST_PATH.'meta'.DIRECTORY_SEPARATOR;
		$path = ONPHP_META_PATH.'bin'.DIRECTORY_SEPARATOR.'build.php';
		
		$_SERVER['argv'][0] = $path;
		
		$_SERVER['argv'][1] = $metaDir.'config.inc.php';
		
		$_SERVER['argv'][2] = $metaDir.'config.meta.xml';
		
		$_SERVER['argv'][] = '--force';
		$_SERVER['argv'][] = '--no-schema-check';
		$_SERVER['argv'][] = '--drop-stale-files';
		
		require $path;
		
		// provide paths to autogenerated stuff
		set_include_path(
			get_include_path().PATH_SEPARATOR
			.ONPHP_META_AUTO_BUSINESS_DIR.PATH_SEPARATOR
			.ONPHP_META_AUTO_DAO_DIR.PATH_SEPARATOR
			.ONPHP_META_AUTO_PROTO_DIR.PATH_SEPARATOR
			
			.ONPHP_META_DAO_DIR.PATH_SEPARATOR
			.ONPHP_META_BUSINESS_DIR.PATH_SEPARATOR
			.ONPHP_META_PROTO_DIR
		);
		
		// provide fake spooked class
		class Spook extends IdentifiableObject {/*_*/}
		
		$test->addTestClass(new DAOTest());
	}
	
	$test->run($reporter);
?>