<?php
/*****************************************************************************
 *   Copyright (C) 2006, onPHP's MetaConfiguration Builder.                  *
 *   Generated by onPHP-0.4.3.99 at 2006-05-07 19:37:11                      *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class AdministratorDAO extends AutoAdministratorDAO
	{
		public function logIn($username, $password)
		{
			return
				$this->getByLogic(
					Expression::expAnd(
						Expression::eq('username', $username),
						Expression::eq('password', $password)
					)
				);
		}
	}
?>