<?php
/*****************************************************************************
 *   Copyright (C) 2006-2007, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-0.11.1.111 at 2007-05-08 17:47:09                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoAdministrator extends AbstractProtoClass
	{
		protected function makePropertyList()
		{
			return array(
				'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'identifier', 'Administrator', null, true, true, false, null, null),
				'username' => LightMetaProperty::fill(new LightMetaProperty(), 'username', null, 'string', null, 64, true, true, false, null, null),
				'password' => LightMetaProperty::fill(new LightMetaProperty(), 'password', null, 'string', null, 40, true, true, false, null, null)
			);
		}
	}
?>