<?php
/*****************************************************************************
 *   Copyright (C) 2006-2007, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-0.9.42 at 2007-03-03 20:44:45                        *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoAdministrator extends AbstractProtoClass
	{
		/**
		 * @return Form
		**/
		public function makeForm()
		{
			return
				Form::create()->
				add(
					Primitive::identifier('id')->
					of('Administrator')->
					required()
				)->
				add(
					Primitive::string('username')->
					required()->
					setMax(64)
				)->
				add(
					Primitive::string('password')->
					required()->
					setMax(40)
				);
		}
		
		protected function makePropertyList()
		{
			return array(
				'id' => LightMetaProperty::make('id', 'id', null, true, true, null, null),
				'username' => LightMetaProperty::make('username', 'username', null, true, true, null, null),
				'password' => LightMetaProperty::make('password', 'password', null, true, true, null, null)
			);
		}
	}
?>