<?php
/*****************************************************************************
 *   Copyright (C) 2006-2007, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-0.9.42 at 2007-01-06 02:29:45                        *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/
/* $Id$ */

	final class ProtoAdministrator extends AbstractProtoClass
	{
		/**
		 * @return MetaClass
		**/
		public function getPropertyList()
		{
			static $list = null;
			
			if (!$list) {
				$list['id'] = LightMetaProperty::make('id', 'id', 'id_id', null, true, false, null);
				$list['username'] = LightMetaProperty::make('username', 'username', null, null, true, false, null);
				$list['password'] = LightMetaProperty::make('password', 'password', null, null, true, false, null);
			}
			
			return $list;
		}
		
		public function makeForm()
		{
			/**
			 * @return Form
			**/
			return
				Form::create()->
				add(
					Primitive::identifier('id')->
					of('Administrator')->
					required()
				)->
				add(
					Primitive::string('username')->
					required()->
					setMax(64)
				)->
				add(
					Primitive::string('password')->
					required()->
					setMax(40)
				);
		}
	}
?>