<?php
/*****************************************************************************
 *   Copyright (C) 2006, onPHP's MetaConfiguration Builder.                  *
 *   Generated by onPHP-0.8.1.99 at 2006-11-12 00:04:33                      *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	final class ProtoAdministrator extends AbstractProtoClass
	{
		public function makeForm()
		{
			/**
			 * @return Form
			**/
			return
				Form::create()->
				add(
					Primitive::identifier('id')->
					of('Administrator')->
					required()
				)->
				add(
					Primitive::string('username')->
					required()->
					setMax(64)
				)->
				add(
					Primitive::string('password')->
					required()->
					setMax(40)
				);
		}
	}
?>