<?php
/*****************************************************************************
 *   Copyright (C) 2006, onPHP's MetaConfiguration Builder.                  *
 *   Generated by onPHP-0.5 at 2006-07-12 19:55:22                           *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	class ProtoAdministrator extends AbstractProtoClass
	{
		private $form = null;
		
		protected function __construct()
		{
			$this->form = $this->makeForm();
		}
		
		public function makeForm()
		{
			return
				Form::create()->
				add(
					Primitive::identifier('id')->
					of('Administrator')->
					required()
				)->
				add(
					Primitive::string('username')->
					required()->
					setMax(64)
				)->
				add(
					Primitive::string('password')->
					required()->
					setMax(40)
				);
		}
	}
?>