<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2012-11-09 13:43:08                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	namespace Onphp\NsConverter;
	
	abstract class AutoNsConstant
	{
		protected $name = null;
		
		/**
		 * @return \Onphp\NsConverter\NsConstant
		**/
		public static function create()
		{
			return new static;
		}
		
		
		/**
		 * @return \Onphp\NsConverter\ProtoNsConstant
		**/
		public static function proto()
		{
			return \Onphp\Singleton::getInstance('\Onphp\NsConverter\ProtoNsConstant');
		}
		
		public function getName()
		{
			return $this->name;
		}
		
		/**
		 * @return \Onphp\NsConverter\NsConstant
		**/
		public function setName($name)
		{
			$this->name = $name;
			
			return $this;
		}
	}
?>