<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2012-10-28 12:28:55                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	namespace Onphp\NsConverter;
	
	abstract class AutoNsClass
	{
		protected $name = null;
		protected $namespace = null;
		protected $newNamespace = null;
		
		public function getName()
		{
			return $this->name;
		}
		
		/**
		 * @return \Onphp\NsConverter\NsClass
		**/
		public function setName($name)
		{
			$this->name = $name;
			
			return $this;
		}
		
		public function getNamespace()
		{
			return $this->namespace;
		}
		
		/**
		 * @return \Onphp\NsConverter\NsClass
		**/
		public function setNamespace($namespace)
		{
			$this->namespace = $namespace;
			
			return $this;
		}
		
		public function getNewNamespace()
		{
			return $this->newNamespace;
		}
		
		/**
		 * @return \Onphp\NsConverter\NsClass
		**/
		public function setNewNamespace($newNamespace)
		{
			$this->newNamespace = $newNamespace;
			
			return $this;
		}
	}
?>