<?php
/*****************************************************************************
 *   Copyright (C) 2006-2007, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-0.9.300 at 2007-05-15 15:33:33                       *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/
/* $Id$ */

	abstract class AutoProtoStatisticQuery extends AbstractProtoClass
	{
		/**
		 * @return Form
		**/
		public function makeForm()
		{
			return
				Form::create()->
				add(
					Primitive::identifier('id')->
					of('StatisticQuery')->
					required()
				)->
				add(
					Primitive::string('query')->
					required()
				)->
				add(
					Primitive::string('media')->
					required()->
					setMax(100)
				)->
				add(
					Primitive::timestamp('when')->
					required()
				)->
				add(
					Primitive::integer('found')->
					setMin(PrimitiveInteger::SIGNED_MIN)->
					setMax(PrimitiveInteger::SIGNED_MAX)->
					required()
				)->
				add(
					Primitive::identifier('region')->
					of('Region')->
					setMin(PrimitiveInteger::SIGNED_MIN)->
					setMax(PrimitiveInteger::SIGNED_MAX)->
					optional()
				)->
				add(
					Primitive::inet('ip')->
					optional()
				);
		}
		
		protected function makePropertyList()
		{
			return array(
				'id' => LightMetaProperty::make('id', 'id', null, true, true, null, null),
				'query' => LightMetaProperty::make('query', 'query', null, true, true, null, null),
				'media' => LightMetaProperty::make('media', 'media', null, true, true, null, null),
				'when' => LightMetaProperty::make('when', 'when', 'Timestamp', true, true, null, null),
				'found' => LightMetaProperty::make('found', 'found', null, true, true, null, null),
				'region' => LightMetaProperty::make('region', 'region_id', 'Region', false, false, 'OneToOne', null),
				'ip' => LightMetaProperty::make('ip', 'ip', null, false, true, null, null)
			);
		}
	}
?>