<?php
/*****************************************************************************
 *   Copyright (C) 2006-2007, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-0.9.300 at 2007-05-15 15:32:37                       *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/
/* $Id$ */

	abstract class AutoProtoRegion extends AbstractProtoClass
	{
		/**
		 * @return Form
		**/
		public function makeForm()
		{
			return
				Form::create()->
				add(
					Primitive::identifier('id')->
					of('Region')->
					setMin(PrimitiveInteger::SIGNED_MIN)->
					setMax(PrimitiveInteger::SIGNED_MAX)->
					required()
				)->
				add(
					Primitive::string('name')->
					required()->
					setMax(255)
				)->
				add(
					Primitive::string('country')->
					optional()->
					setMax(100)
				)->
				add(
					Primitive::identifier('parent')->
					of('Region')->
					setMin(PrimitiveInteger::SIGNED_MIN)->
					setMax(PrimitiveInteger::SIGNED_MAX)->
					optional()
				);
		}
		
		protected function makePropertyList()
		{
			return array(
				'id' => LightMetaProperty::make('id', 'id', null, true, true, null, null),
				'name' => LightMetaProperty::make('name', 'name', null, true, true, null, null),
				'country' => LightMetaProperty::make('country', 'country', null, false, true, null, null),
				'parent' => LightMetaProperty::make('parent', 'parent_id', 'Region', false, false, 'OneToOne', 2)
			);
		}
	}
?>