<?php
/*****************************************************************************
 *   Copyright (C) 2006-2007, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-0.9.300 at 2007-05-15 14:27:41                       *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/
/* $Id$ */

	abstract class AutoProtoStatisticClick extends AbstractProtoClass
	{
		/**
		 * @return Form
		**/
		public function makeForm()
		{
			return
				Form::create()->
				add(
					Primitive::identifier('id')->
					of('StatisticClick')->
					required()
				)->
				add(
					Primitive::identifier('query')->
					of('StatisticQuery')->
					required()
				)->
				add(
					Primitive::timestamp('when')->
					required()
				)->
				add(
					Primitive::string('site')->
					required()
				);
		}
		
		protected function makePropertyList()
		{
			return array(
				'id' => LightMetaProperty::make('id', 'id', null, true, true, null, null),
				'query' => LightMetaProperty::make('query', 'query_id', 'StatisticQuery', true, false, 'OneToOne', null),
				'when' => LightMetaProperty::make('when', 'when', 'Timestamp', true, true, null, null),
				'site' => LightMetaProperty::make('site', 'site', null, true, true, null, null)
			);
		}
	}
?>