<?php
/*****************************************************************************
 *   Copyright (C) 2006-2007, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-0.11.1.111 at 2007-12-18 18:27:00                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoStatisticVisitor extends AbstractProtoClass
	{
		protected function makePropertyList()
		{
			return array(
				'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'identifier', 'StatisticVisitor', null, true, true, false, null, null),
				'when' => LightMetaProperty::fill(new LightMetaProperty(), 'when', null, 'timestamp', 'Timestamp', null, true, true, false, null, null),
				'region' => LightMetaProperty::fill(new LightMetaProperty(), 'region', 'region_id', 'identifier', 'Region', null, false, false, false, 1, null),
				'ip' => LightMetaProperty::fill(new LightMetaProperty(), 'ip', null, 'inet', null, null, false, true, false, null, null)
			);
		}
	}
?>