<?php
/*****************************************************************************
 *   Copyright (C) 2006-2007, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-0.9.300 at 2007-05-15 14:27:41                       *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class RegionDAO extends AutoRegionDAO
	{
		// your brilliant stuff goes here
	}
?>