<?php
/*****************************************************************************
 *   Copyright (C) 2006-2007, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-0.9.300 at 2007-05-15 14:27:41                       *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoStatisticClick extends IdentifiableObject
	{
		protected $query = null;
		protected $when = null;
		protected $site = null;
		
		/**
		 * @return StatisticQuery
		**/
		public function getQuery()
		{
			return $this->query;
		}
		
		/**
		 * @return StatisticClick
		**/
		public function setQuery(StatisticQuery $query)
		{
			$this->query = $query;
			
			return $this;
		}
		
		/**
		 * @return StatisticClick
		**/
		public function dropQuery()
		{
			$this->query = null;
			
			return $this;
		}
		
		/**
		 * @return Timestamp
		**/
		public function getWhen()
		{
			return $this->when;
		}
		
		/**
		 * @return StatisticClick
		**/
		public function setWhen(Timestamp $when)
		{
			$this->when = $when;
			
			return $this;
		}
		
		/**
		 * @return StatisticClick
		**/
		public function dropWhen()
		{
			$this->when = null;
			
			return $this;
		}
		
		public function getSite()
		{
			return $this->site;
		}
		
		/**
		 * @return StatisticClick
		**/
		public function setSite($site)
		{
			$this->site = $site;
			
			return $this;
		}
	}
?>