<?php
/*****************************************************************************
 *   Copyright (C) 2006-2007, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-0.9.300 at 2007-05-15 14:27:41                       *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoStatisticVisitor extends IdentifiableObject
	{
		protected $when = null;
		protected $region = null;
		protected $ip = null;
		
		/**
		 * @return Timestamp
		**/
		public function getWhen()
		{
			return $this->when;
		}
		
		/**
		 * @return StatisticVisitor
		**/
		public function setWhen(Timestamp $when)
		{
			$this->when = $when;
			
			return $this;
		}
		
		/**
		 * @return StatisticVisitor
		**/
		public function dropWhen()
		{
			$this->when = null;
			
			return $this;
		}
		
		/**
		 * @return Region
		**/
		public function getRegion()
		{
			return $this->region;
		}
		
		/**
		 * @return StatisticVisitor
		**/
		public function setRegion(Region $region)
		{
			$this->region = $region;
			
			return $this;
		}
		
		/**
		 * @return StatisticVisitor
		**/
		public function dropRegion()
		{
			$this->region = null;
			
			return $this;
		}
		
		public function getIp()
		{
			return $this->ip;
		}
		
		/**
		 * @return StatisticVisitor
		**/
		public function setIp($ip)
		{
			$this->ip = $ip;
			
			return $this;
		}
	}
?>