<?php
/*****************************************************************************
 *   Copyright (C) 2006-2007, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-0.9.300 at 2007-05-15 14:27:41                       *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class StatisticVisitor extends AutoStatisticVisitor implements Prototyped, DAOConnected
	{
		/**
		 * @return StatisticVisitor
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return StatisticVisitorDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('StatisticVisitorDAO');
		}
		
		/**
		 * @return ProtoStatisticVisitor
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoStatisticVisitor');
		}
		
		// your brilliant stuff goes here
	}
?>