<?php
/*****************************************************************************
 *   Copyright (C) 2006, onPHP's MetaConfiguration Builder.                  *
 *   Generated by onPHP-0.8.0.99 at 2006-10-25 13:27:45                      *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/
/* $Id$ */

	abstract class AutoAdministratorDAO extends StorableDAO
	{
		protected $mapping = array(
			'id' => null,
			'username' => null,
			'password' => null
		);
		
		public function getTable()
		{
			return 'administrator';
		}
		
		public function getObjectName()
		{
			return 'Administrator';
		}
		
		public function getSequence()
		{
			return 'administrator_id';
		}
		
		public function setQueryFields(InsertOrUpdateQuery $query, Administrator $administrator)
		{
			return
				$query->
					set('id', $administrator->getId())->
					set('username', $administrator->getUsername())->
					set('password', $administrator->getPassword());
		}
		
		public function makeObject(&$array, $prefix = null)
		{
			return $this->fillObject(new Administrator(), $array, $prefix);
		}
		
		protected function fillObject(/* Administrator */ $administrator, &$array, $prefix = null)
		{
			$administrator->
				setId($array[$prefix.'id'])->
				setUsername($array[$prefix.'username'])->
				setPassword($array[$prefix.'password']);
				
			return $administrator;
		}
	}
?>