<?php
/*****************************************************************************
 *   Copyright (C) 2006-2007, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-0.9.128 at 2007-03-31 16:25:48                       *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/
/* $Id$ */

	abstract class AutoAdministratorDAO extends ComplexBuilderDAO
	{
		public function getTable()
		{
			return 'administrator';
		}
		
		public function getObjectName()
		{
			return 'Administrator';
		}
		
		public function getSequence()
		{
			return 'administrator_id';
		}
		
		/**
		 * @return InsertOrUpdateQuery
		**/
		public function setQueryFields(InsertOrUpdateQuery $query, Administrator $administrator)
		{
			return
				$query->
					set('id', $administrator->getId())->
					set('username', $administrator->getUsername())->
					set('password', $administrator->getPassword());
		}
		
		/**
		 * @return Administrator
		**/
		protected function makeSelf(&$array, $prefix = null)
		{
			$administrator = new Administrator();
			
			$administrator->
				setId($array[$prefix.'id'])->
				setUsername($array[$prefix.'username'])->
				setPassword($array[$prefix.'password']);
			
			return $administrator;
		}
	}
?>