<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2012-10-28 12:28:55                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	namespace Onphp\NsConverter;
	
	class NsClass extends AutoNsClass implements \Onphp\Prototyped
	{
		/**
		 * @return \Onphp\NsConverter\NsClass
		**/
		public static function create()
		{
			return new self;
		}
		
		
		/**
		 * @return \Onphp\NsConverter\ProtoNsClass
		**/
		public static function proto()
		{
			return \Onphp\Singleton::getInstance('\Onphp\NsConverter\ProtoNsClass');
		}
		
		// your brilliant stuff goes here
		
		public function getFullName()
		{
			return $this->getNamespace().$this->getName();
		}
		
		public function getFullNewName($newNs = null)
		{
			if ($newNs) {
				$newNs = NamespaceUtils::fixNamespace($newNs);
				if ($newNs == $this->getNewNamespace()) {
					return $this->getName();
				}
			}
			return $this->getNewNamespace().$this->getName();
		}
		
		/**
		 * @param string $namespace
		 * @return \Onphp\NsConverter\NsClass
		 */
		public function setNamespace($namespace)
		{
			return parent::setNamespace(NamespaceUtils::fixNamespace($namespace));
		}
		
		public function setNewNamespace($newNamespace)
		{
			return parent::setNewNamespace(NamespaceUtils::fixNamespace($newNamespace));
		}
	}