<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2012-11-09 13:43:08                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	namespace Onphp\NsConverter;

	class NsFunction extends \Onphp\NsConverter\AutoNsFunction implements \Onphp\Prototyped
	{
		public function getFullName()
		{
			return $this->getNamespace().$this->getName();
		}

		public function getFullNewName($newNs = null)
		{
			if ($newNs) {
				$newNs = NamespaceUtils::fixNamespace($newNs);
				if ($newNs == $this->getNewNamespace()) {
					return $this->getName();
				}
			}
			return $this->getNewNamespace().$this->getName();
		}

		/**
		 * @param string $namespace
		 * @return \Onphp\NsConverter\NsClass
		 */
		public function setNamespace($namespace)
		{
			return parent::setNamespace(NamespaceUtils::fixNamespace($namespace));
		}

		public function setNewNamespace($newNamespace)
		{
			return parent::setNewNamespace(NamespaceUtils::fixNamespace($newNamespace));
		}
	}
?>