<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2012-10-28 12:28:55                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

namespace Onphp\NsConverter\Business;

use \Onphp\Enum;

class ActionEnum extends Enum
{
	const SCAN = 'scan';
	const SCAN_NEW = 'scanNew';
	const SCAN_OLD = 'scanOld';
	const CONFIG = 'config';
	const REPLACE = 'replace';

	protected static $names = [
		self::SCAN => 'scan project as converting old => new',
		self::SCAN_NEW => 'scan project only as new namespaces',
		self::SCAN_OLD => 'scan project only as old namespaces',
		self::CONFIG => 'config dir/path',
		self::REPLACE => 'replace',
	];
}