<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2012-10-28 12:28:55                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	namespace Onphp\NsConverter\Business;

	use \Onphp\NsConverter\Auto\Business\AutoNsClass as AutoNsClass;
	use \Onphp\Prototyped as Prototyped;
	use \Onphp\NsConverter\Utils\NamespaceUtils as NamespaceUtils;

	class NsClass extends AutoNsClass implements Prototyped
	{
		public function getFullName()
		{
			return $this->getNamespace().$this->getName();
		}

		public function getFullNewName()
		{
			return $this->getNewNamespace().$this->getName();
		}

		/**
		 * @param string $namespace
		 * @return NsClass
		 */
		public function setNamespace($namespace)
		{
			return parent::setNamespace(NamespaceUtils::fixNamespace($namespace));
		}

		public function setNewNamespace($newNamespace)
		{
			return parent::setNewNamespace(NamespaceUtils::fixNamespace($newNamespace));
		}
	}