<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2012-11-09 13:43:08                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	namespace Onphp\NsConverter\Business;

	use \Onphp\NsConverter\Auto\Business\AutoNsConstant as AutoNsConstant;
	use \Onphp\Prototyped as Prototyped;
	
	class NsConstant extends AutoNsConstant implements Prototyped
	{
		// your brilliant stuff goes here
	}
?>