<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2012-11-09 13:43:08                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	namespace Onphp\NsConverter\Proto;

	use \Onphp\NsConverter\Auto\Proto\AutoProtoNsFunction as AutoProtoNsFunction;
	
	class ProtoNsFunction extends AutoProtoNsFunction {/*_*/}
?>