<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2012-11-09 13:41:54                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	$schema = new \Onphp\DBSchema();
	
?>