<?php
/*****************************************************************************
 *   Copyright (C) 2006-2007, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-0.9.300 at 2007-05-15 15:33:33                       *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/
/* $Id$ */

	abstract class AutoStatisticVisitorDAO extends ComplexBuilderDAO
	{
		public function getTable()
		{
			return 'statistic_visitor';
		}
		
		public function getObjectName()
		{
			return 'StatisticVisitor';
		}
		
		public function getSequence()
		{
			return 'statistic_visitor_id';
		}
		
		/**
		 * @return InsertOrUpdateQuery
		**/
		public function setQueryFields(InsertOrUpdateQuery $query, StatisticVisitor $statisticVisitor)
		{
			return
				$query->
					set('id', $statisticVisitor->getId())->
					set('when', $statisticVisitor->getWhen()->toString())->
					set(
						'region_id',
						$statisticVisitor->getRegion()
							? $statisticVisitor->getRegion()->getId()
							: null
					)->
					set('ip', ip2long($statisticVisitor->getIp()));
		}
		
		/**
		 * @return StatisticVisitor
		**/
		protected function makeSelf(&$array, $prefix = null)
		{
			$statisticVisitor = new StatisticVisitor();
			
			$statisticVisitor->
				setId($array[$prefix.'id'])->
				setWhen(new Timestamp($array[$prefix.'when']))->
				setIp(
					isset($array[$prefix.'ip'])
						? long2ip($array[$prefix.'ip'])
						: null
				);
			
			return $statisticVisitor;
		}
		
		/**
		 * @return StatisticVisitor
		**/
		protected function makeCascade(/* StatisticVisitor */ $statisticVisitor, &$array, $prefix = null)
		{
			if (isset($array[$prefix.'region_id'])) {
				$statisticVisitor->setRegion(
					Region::dao()->getById($array[$prefix.'region_id'])
				);
			}
			
			return $statisticVisitor;
		}
		
		/**
		 * @return StatisticVisitor
		**/
		protected function makeJoiners(/* StatisticVisitor */ $statisticVisitor, &$array, $prefix = null)
		{
			if (isset($array[Region::dao()->getJoinPrefix('region_id', $prefix).'id'])) {
				$statisticVisitor->setRegion(
					Region::dao()->makeJoinedObject($array, Region::dao()->getJoinPrefix('region_id', $prefix))
				);
			}
			
			return $statisticVisitor;
		}
	}
?>