<?php
/*****************************************************************************
 *   Copyright (C) 2006-2007, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-0.9.300 at 2007-05-15 15:33:33                       *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/
/* $Id$ */

	abstract class AutoStatisticQueryDAO extends ComplexBuilderDAO
	{
		public function getTable()
		{
			return 'statistic_query';
		}
		
		public function getObjectName()
		{
			return 'StatisticQuery';
		}
		
		public function getSequence()
		{
			return 'statistic_query_id';
		}
		
		public function uncacheLists()
		{
			StatisticClick::dao()->uncacheLists();
			
			return parent::uncacheLists();
		}
		
		/**
		 * @return InsertOrUpdateQuery
		**/
		public function setQueryFields(InsertOrUpdateQuery $query, StatisticQuery $statisticQuery)
		{
			return
				$query->
					set('id', $statisticQuery->getId())->
					set('query', $statisticQuery->getQuery())->
					set('media', $statisticQuery->getMedia())->
					set('when', $statisticQuery->getWhen()->toString())->
					set('found', $statisticQuery->getFound())->
					set(
						'region_id',
						$statisticQuery->getRegion()
							? $statisticQuery->getRegion()->getId()
							: null
					)->
					set('ip', ip2long($statisticQuery->getIp()));
		}
		
		/**
		 * @return StatisticQuery
		**/
		protected function makeSelf(&$array, $prefix = null)
		{
			$statisticQuery = new StatisticQuery();
			
			$statisticQuery->
				setId($array[$prefix.'id'])->
				setQuery($array[$prefix.'query'])->
				setMedia($array[$prefix.'media'])->
				setWhen(new Timestamp($array[$prefix.'when']))->
				setFound($array[$prefix.'found'])->
				setIp(
					isset($array[$prefix.'ip'])
						? long2ip($array[$prefix.'ip'])
						: null
				);
			
			return $statisticQuery;
		}
		
		/**
		 * @return StatisticQuery
		**/
		protected function makeCascade(/* StatisticQuery */ $statisticQuery, &$array, $prefix = null)
		{
			if (isset($array[$prefix.'region_id'])) {
				$statisticQuery->setRegion(
					Region::dao()->getById($array[$prefix.'region_id'])
				);
			}
			
			return $statisticQuery;
		}
		
		/**
		 * @return StatisticQuery
		**/
		protected function makeJoiners(/* StatisticQuery */ $statisticQuery, &$array, $prefix = null)
		{
			if (isset($array[Region::dao()->getJoinPrefix('region_id', $prefix).'id'])) {
				$statisticQuery->setRegion(
					Region::dao()->makeJoinedObject($array, Region::dao()->getJoinPrefix('region_id', $prefix))
				);
			}
			
			return $statisticQuery;
		}
	}
?>