<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2012-11-09 13:43:08                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	namespace Onphp\NsConverter\Auto\Proto;

	use \Onphp\AbstractProtoClass;
	use \Onphp\LightMetaProperty;

	abstract class AutoProtoNsFunction extends AbstractProtoClass
	{
		protected function makePropertyList()
		{
			return array(
				'name' => LightMetaProperty::fill(new LightMetaProperty(), 'name', null, 'string', null, 256, true, true, false, null, null),
				'namespace' => LightMetaProperty::fill(new LightMetaProperty(), 'namespace', null, 'string', null, 256, true, true, false, null, null),
				'newNamespace' => LightMetaProperty::fill(new LightMetaProperty(), 'newNamespace', 'new_namespace', 'string', null, 256, true, true, false, null, null)
			);
		}
	}
?>