<?php
/*****************************************************************************
 *   Copyright (C) 2006, onPHP's MetaConfiguration Builder.                  *
 *   Generated by onPHP-0.8.1.99 at 2006-11-12 00:04:33                      *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoAdministrator extends IdentifiableObject
	{
		protected $username = null;
		protected $password = null;
		
		public function getUsername()
		{
			return $this->username;
		}
		
		/**
		 * @return Administrator
		**/
		public function setUsername($username)
		{
			$this->username = $username;
			
			return $this;
		}
		
		public function getPassword()
		{
			return $this->password;
		}
		
		/**
		 * @return Administrator
		**/
		public function setPassword($password)
		{
			$this->password = $password;
			
			return $this;
		}
	}
?>