<?php
/*****************************************************************************
 *   Copyright (C) 2006-2007, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-0.9.42 at 2007-01-06 02:29:45                        *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/
/* $Id$ */

	abstract class AutoAdministrator extends IdentifiableObject
	{
		protected $username = null;
		protected $password = null;
		
		public function getUsername()
		{
			return $this->username;
		}
		
		/**
		 * @return Administrator
		**/
		public function setUsername($username)
		{
			$this->username = $username;
			
			return $this;
		}
		
		public function getPassword()
		{
			return $this->password;
		}
		
		/**
		 * @return Administrator
		**/
		public function setPassword($password)
		{
			$this->password = $password;
			
			return $this;
		}
	}
?>