<?php
/*****************************************************************************
 *   Copyright (C) 2006, onPHP's MetaConfiguration Builder.                  *
 *   Generated by onPHP-0.8.0.99 at 2006-10-25 13:27:45                      *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/
/* $Id$ */

	final class ProtoAdministrator extends AbstractProtoClass
	{
		public function makeForm()
		{
			return
				Form::create()->
				add(
					Primitive::identifier('id')->
					of('Administrator')->
					required()
				)->
				add(
					Primitive::string('username')->
					required()->
					setMax(64)
				)->
				add(
					Primitive::string('password')->
					required()->
					setMax(40)
				);
		}
	}
?>