<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.2.master at 2012-11-09 13:55:52                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	namespace Onphp\NsConverter\Auto\Business;

	use \Onphp\NsConverter\Utils\NsObject as NsObject;
	use \Onphp\Singleton as Singleton;
	use \Onphp\NsConverter\Business\NsClass as NsClass;
	use \Onphp\NsConverter\Proto\ProtoNsClass as ProtoNsClass;
	
	abstract class AutoNsClass implements NsObject
	{
		protected $name = null;
		protected $namespace = null;
		protected $newNamespace = null;
		
		/**
		 * @return NsClass
		**/
		public static function create()
		{
			return new static;
		}
		
		
		/**
		 * @return ProtoNsClass
		**/
		public static function proto()
		{
			return Singleton::getInstance('\Onphp\NsConverter\Proto\ProtoNsClass');
		}
		
		public function getName()
		{
			return $this->name;
		}
		
		/**
		 * @return NsClass
		**/
		public function setName($name)
		{
			$this->name = $name;
			
			return $this;
		}
		
		public function getNamespace()
		{
			return $this->namespace;
		}
		
		/**
		 * @return NsClass
		**/
		public function setNamespace($namespace)
		{
			$this->namespace = $namespace;
			
			return $this;
		}
		
		public function getNewNamespace()
		{
			return $this->newNamespace;
		}
		
		/**
		 * @return NsClass
		**/
		public function setNewNamespace($newNamespace)
		{
			$this->newNamespace = $newNamespace;
			
			return $this;
		}
	}
?>