<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2012-10-28 12:28:55                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	namespace Onphp\NsConverter;
	
	class ProtoNsClass extends AutoProtoNsClass {/*_*/}
?>