<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.8.99 at 2009-04-28 17:31:22                      *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/
/* $Id$ */

	final class TestTypeObjectsDAO extends ManyToManyLinked
	{
		public function __construct(TestType $testType, $lazy = false)
		{
			parent::__construct(
				$testType,
				TestObject::dao(),
				$lazy
			);
		}
		
		/**
		 * @return TestTypeObjectsDAO
		**/
		public static function create(TestType $testType, $lazy = false)
		{
			return new self($testType, $lazy);
		}
		
		public function getHelperTable()
		{
			return 'test_type_test_object';
		}
		
		public function getChildIdField()
		{
			return 'test_object_id';
		}
		
		public function getParentIdField()
		{
			return 'test_type_id';
		}
	}
?>